export const GET_PROJECTS = 'GET_PROJECTS';
export const GETTING_COLLECTION = 'GETTING_COLLECTION';
export const REMOVE_VEHICLE_CARD = 'REMOVE_VEHICLE_CARD';
export const POSTING_COLLECTION = 'POSTING_COLLECTION';
export const FETCH_IMAGE = 'FETCH_IMAGE';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';


//CONTACT PAGE 
export const EMAIL_ACTION = 'EMAIL_ACTION';
export const SEND_EMAIL = 'SEND_EMAIL';


//AUTH
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING = 'USER_LOADING';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const AUTH_ERR = 'AUTH_ERR';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESFUL';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';



//ERROR MESSAGES
export const ERROR_MSG = 'ERROR_MSG';
export const REMOVE_ERROR = 'REMOVE_ERROR';